clients:
  - name: Dollar Shave Club
    hooks:
      - ***REMOVED***
  - name: Ingram Micro ( Shipwire )
    hooks:
      - ***REMOVED***
  - name: Hutch Interiors
    hooks:
      - ***REMOVED***
  - name: Taos Internal
    hooks:
      - ***REMOVED***
    hours: 120
  - name: Silicon Valley Bank
    hours: 240

globalHooks:
- ***REMOVED***

default_hours: 80
