customers:
  - name: Acme Corp.
    hours: 120
    recipients:
      emails:
        - <email address here>
      slack:
        - <Slack webhook OR \#channel OR @user>
      teams:
        - <Teams webhook here>
        
#Recipients for all clients below.
recipients:
  slack:
    - <Slack webhook OR \#channel OR @user>
  emails:
    - <email address here>

# Configuration on where to alert on error
exceptions:
  slack:
    - <Slack webhook OR \#channel OR @user>
