clients:
  - name: LotsOfHours
    hours: 160
    hooks:
      - https://hooks.slack.com/services/dude/what!

  - name: Normal Amount of hours
    hooks:
      - https://hooks.slack.com/services/dude/less!

  - name: Direct Message
    hooks:
      - UID!

  - name: MS Teams Hours
    hours: 240
    hooks:
      - https://outlook.office.com/webhook/lotsOfhashes

  - name: Email Only
    hours: 160
    hooks:
      - primary@emailonly.com
      - secondary@emailonly.com

  - name: All Defaults with No Hooks

globalHooks:
  - https://hooks.slack.com/services/GlobalHooksForAllClients
  - myEmailForAllclients@emailsforall.com
  - AnotherOne@emailsforall.com

default_hours: 80

# Can comment out this filter to show all clients
client_filter:
  - Direct Message
  - Email Only
