name: Deploy Cloud Function for Branch

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Setup gcloud environment
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0.2.0
      with:
        version: 296.0.1 # optional, default is 275.0.0
        service_account_email: ${{ secrets.DEPLOYER_SERVICE_ACCOUNT_EMAIL }}
        service_account_key: ${{ secrets.DEPLOYER_SERVICE_ACCOUNT_JSON_CREDENTIALS }}

    - name: Deploy Cloud Function
      run: |-
        gcloud functions deploy harvest-reports-${{ steps.extract_branch.outputs.branch }} \
          --project ${{ secrets.GCP_PROJECT }} \
          --runtime python37 \
          --region us-central1 \
          --entry-point harvest_reports \
          --trigger-topic harvest-reports-${{ steps.extract_branch.outputs.branch }} \
          --set-env-vars HARVEST_ACCOUNT_ID=${{ secrets.HARVEST_ACCOUNT_ID }},BUCKET=${{ secrets.BUCKET }},CONFIG_PATH=harvest-reports-${{ steps.extract_branch.outputs.branch }}.yaml,LOG_LEVEL=debug,ORIGIN_EMAIL_ADDRESS=${{ secrets.ORIGIN_EMAIL_ADDRESS }} \
          --service-account ${{ secrets.RUNNER_SERVICE_ACCOUNT_EMAIL }} \
          --timeout 500