name: Development, Create Branch Config

on: 
  push:
    branches-ignore: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Setup gcloud environment
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.2.0
      with:
        version: 296.0.1 # optional, default is 275.0.0
        service_account_email: ${{ secrets.DEPLOYER_SERVICE_ACCOUNT_EMAIL }}
        service_account_key: ${{ secrets.DEPLOYER_SERVICE_ACCOUNT_JSON_CREDENTIALS }}

    - name: Check If Test Config Exists for Development
      shell: bash
      run: echo "##[set-output name=bool;]$(gsutil -q stat gs://${{ secrets.BUCKET }}/harvest-reports-${{ steps.extract_branch.outputs.branch }}.yaml; echo $?)"
      id: test_config_exists

    - name: Make a Copy of Test Config for Development
      shell: bash
      run: |-
        if [ ${{ steps.test_config_exists.outputs.bool }} = 0 ]; then echo "Test config already exists"; else gsutil cp examples/config.yaml gs://${{ secrets.BUCKET }}/harvest-reports-${{ steps.extract_branch.outputs.branch }}.yaml; fi