name: Development, Delete Branch Environment

on: 
  delete:
    branches-ignore: 
      - master

jobs:
  clean-up:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Setup gcloud environment
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.2
      with:
        version: 296.0.1 # optional, default is 275.0.0
        service_account_email: ${{ secrets.DEPLOYER_SERVICE_ACCOUNT_EMAIL }}
        service_account_key: ${{ secrets.DEPLOYER_SERVICE_ACCOUNT_JSON_CREDENTIALS }}

    - name: Delete Cloud Function
      run: |-
        gcloud functions delete harvest-reports-${{ steps.extract_branch.outputs.branch }}

    - name: Delete Pub/Sub
      run: |-
        gcloud pubsub topics delete harvest-reports-${{ steps.extract_branch.outputs.branch }}

    - name: Delete Object in Bucket
      run: |-
        gsutil rm gs://${{ secrets.bucket }}/harvest-reports-${{ steps.extract_branch.outputs.branch }}